start footer
likeJeka/anatolii-top pull request #5
Opened 2023-05-04 21:30 UTC by OleksandrTsurkan

Воно хоч працює? В мене чогось css не підключався

2023-05-04 21:41 UTC, Chapelk1 approved these changes

2023-05-04 21:47 UTC, Chapelk1 requested changes

2023-05-04 21:47 UTC, Chapelk1 commented on src/partials/footer.html
> +<link rel="stylesheet" href="../css/styles.css"/>
они все подключены в главный style.html

2023-05-04 21:49 UTC, Chapelk1 commented on src/partials/footer.html
> +<link rel="stylesheet" href="../css/styles.css"/>
ты обновлял себе мейн? у тебя в ветке удалены почти все строчки в файле package-lock.json

2023-05-04 21:50 UTC, Chapelk1 commented on src/partials/footer.html
> +<link rel="stylesheet" href="../css/styles.css"/>
npm ci в терминал, перед работой прописывал?

2023-05-06 22:06 UTC, hoocher commented on src/partials/footer.html
> +<link rel="stylesheet" href="../css/styles.css"/>
В мене показує таку дич. щось в теьбе не так.
![image](https://user-images.githubusercontent.com/120508000/236648287-3bb02946-21f7-4f07-951c-c67172a4fe50.png)

2023-05-07 10:51 UTC, closed without merging